---

language: python

python: "2.7"

dist: trusty

sudo: required

addons:
  apt:
    packages:
      - python-pip

before_install:
  - pip install ansible
  - ansible --version

install:
  - printf '[defaults]\nroles_path=../' >ansible.cfg

script:
  - sudo ansible-playbook tests/test.yml -i tests/hosts --syntax-check
  - sudo ansible-playbook tests/test.yml -i tests/hosts
  - sudo ansible-playbook tests/test.yml -i tests/hosts | grep -q 'unreachable=0.*failed=0' && exit 0 || exit 1

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
