---

sudo: required

dist: trusty

language: generic

before_install:
  - sudo apt-add-repository -y ppa:fkrull/deadsnakes-python2.7
  - sudo apt-get update
  - sudo apt-get -y install python2.7

install:
  - printf '[defaults]\nroles_path=../' > ansible.cfg
  - pip install ansible
  - ansible --version

script:
  - ansible-playbook tests/test.yml -i tests/hosts --syntax-check
  - ansible-playbook tests/test.yml -i tests/hosts
  - ansible-playbook tests/test.yml -i tests/hosts | grep -q 'unreachable=0.*failed=0' && exit 0 || exit 1

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
