---

language: python

python: "2.7"

sudo: false

addons:
  apt:
    packages:
      - python-pip

before_install:
  - pip install -r requirements.txt
  - ansible --version

install:
  - printf '[defaults]\nroles_path=../' > ansible.cfg

script:
  - ansible-playbook tests/test.yml -i tests/hosts --syntax-check
  - ansible-playbook tests/test.yml -i tests/hosts
  - ansible-playbook tests/test.yml -i tests/hosts | grep -q 'unreachable=0.*failed=0' && exit 0 || exit 1

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
