---
# tasks file for docker

- name: include release specific variables
  include_vars: "{{ ansible_distribution_release }}.yml"
  tags: docker

- name: apt-get install
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items:
    - { state: "present", name: "apt-transport-https" }
    - { state: "present", name: "ca-certificates" }
    - { state: "present", name: "curl" }
    - { state: "present", name: "software-properties-common" }
  tags: docker

- name: apt-key add
  apt_key:
    url: "{{ item.url }}"
    state: "{{ item.state }}"
  with_items: "{{ _apt_key }}"
  tags: docker

- name: apt-add-repository
  apt_repository:
    repo: "{{ item.repo }}"
    state: "{{ item.state }}"
  with_items: "{{ _apt_repository }}"
  tags: docker

- name: apt-get install
  apt:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ _apt }}"
  tags: docker

- name: pip install
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ _pip }}"
  tags: docker

- name: enable service
  service:
    name: "{{ item.name }}"
    enabled: "{{ item.enabled }}"
  with_items:
    - { name: "docker", enabled: "yes" }
  notify: restart docker
  tags: docker
