---

# (c) Wong Hoi Sing Edison <hswong3i@pantarei-design.com>
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: include release specific variables
  include_vars: "{{ loop_var }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  loop_control:
    loop_var: "loop_var"
  tags: docker

- name: include release specific tasks
  include: "{{ loop_var }}"
  with_first_found:
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
    - "{{ ansible_distribution | lower }}.yml"
    - "{{ ansible_os_family | lower }}.yml"
  loop_control:
    loop_var: "loop_var"
  tags: docker

- name: pip install
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
  with_items: "{{ _pip }}"
  notify: restart docker
  tags: docker

- name: enable service
  service:
    name: "docker"
    enabled: "yes"
  notify: restart docker
  tags: docker

- name: docker pull
  docker_image:
    api_version: "{{ item.api_version | default(None) or omit }}"
    archive_path: "{{ item.archive_path | default(None) or omit }}"
    buildargs: "{{ item.buildargs | default(None) or omit }}"
    cacert_path: "{{ item.cacert_path | default(None) or omit }}"
    cert_path: "{{ item.cert_path | default(None) or omit }}"
    container_limits: "{{ item.container_limits | default(None) or omit }}"
    cpusetcpus: "{{ item.cpusetcpus | default(None) or omit }}"
    cpushares: "{{ item.cpushares | default(None) or omit }}"
    key_path: "{{ item.key_path | default(None) or omit }}"
    load_path: "{{ item.load_path | default(None) or omit }}"
    memory: "{{ item.memory | default(None) or omit }}"
    memswap: "{{ item.memswap | default(None) or omit }}"
    name: "{{ item.name | default(None) or omit }}"
    nocache: "{{ item.nocache | default(None) or omit }}"
    path: "{{ item.path | default(None) or omit }}"
    pull: "{{ item.pull | default(None) or omit }}"
    push: "{{ item.push | default(None) or omit }}"
    repository: "{{ item.repository | default(None) or omit }}"
    rm: "{{ item.rm | default(None) or omit }}"
    ssl_version: "{{ item.ssl_version | default(None) or omit }}"
    state: "{{ item.state | default(None) or omit }}"
    tag: "{{ item.tag | default(None) or omit }}"
    timeout: "{{ item.timeout | default(None) or omit }}"
    tls: "{{ item.tls | default(None) or omit }}"
    tls_hostname: "{{ item.tls_hostname | default(None) or omit }}"
    tls_verify: "{{ item.tls_verify | default(None) or omit }}"
    use_tls: "{{ item.use_tls | default(None) or omit }}"
  with_items: "{{ docker_image }}"
  tags: docker

- name: docker run
  docker_container:
    api_version: "{{ item.api_version | default(None) or omit }}"
    auto_remove: "{{ item.auto_remove | default(None) or omit }}"
    blkio_weight: "{{ item.blkio_weight | default(None) or omit }}"
    cacert_path: "{{ item.cacert_path | default(None) or omit }}"
    capabilities: "{{ item.capabilities | default(None) or omit }}"
    cert_path: "{{ item.cert_path | default(None) or omit }}"
    cleanup: "{{ item.cleanup | default(None) or omit }}"
    command: "{{ item.command | default(None) or omit }}"
    cpu_period: "{{ item.cpu_period | default(None) or omit }}"
    cpu_quota: "{{ item.cpu_quota | default(None) or omit }}"
    cpu_shares: "{{ item.cpu_shares | default(None) or omit }}"
    cpuset_cpus: "{{ item.cpuset_cpus | default(None) or omit }}"
    cpuset_mems: "{{ item.cpuset_mems | default(None) or omit }}"
    detach: "{{ item.detach | default(None) or omit }}"
    devices: "{{ item.devices | default(None) or omit }}"
    dns_search_domains: "{{ item.dns_search_domains | default(None) or omit }}"
    dns_servers: "{{ item.dns_servers | default(None) or omit }}"
    docker_host: "{{ item.docker_host | default(None) or omit }}"
    entrypoint: "{{ item.entrypoint | default(None) or omit }}"
    env: "{{ item.env | default(None) or omit }}"
    env_file: "{{ item.env_file | default(None) or omit }}"
    etc_hosts: "{{ item.etc_hosts | default(None) or omit }}"
    exposed_ports: "{{ item.exposed_ports | default(None) or omit }}"
    force_kill: "{{ item.force_kill | default(None) or omit }}"
    groups: "{{ item.groups | default(None) or omit }}"
    hostname: "{{ item.hostname | default(None) or omit }}"
    ignore_image: "{{ item.ignore_image | default(None) or omit }}"
    image: "{{ item.image | default(None) or omit }}"
    interactive: "{{ item.interactive | default(None) or omit }}"
    ipc_mode: "{{ item.ipc_mode | default(None) or omit }}"
    keep_volumes: "{{ item.keep_volumes | default(None) or omit }}"
    kernel_memory: "{{ item.kernel_memory | default(None) or omit }}"
    key_path: "{{ item.key_path | default(None) or omit }}"
    kill_signal: "{{ item.kill_signal | default(None) or omit }}"
    labels: "{{ item.labels | default(None) or omit }}"
    links: "{{ item.links | default(None) or omit }}"
    log_driver: "{{ item.log_driver | default(None) or omit }}"
    log_options: "{{ item.log_options | default(None) or omit }}"
    mac_address: "{{ item.mac_address | default(None) or omit }}"
    memory: "{{ item.memory | default(None) or omit }}"
    memory_reservation: "{{ item.memory_reservation | default(None) or omit }}"
    memory_swap: "{{ item.memory_swap | default(None) or omit }}"
    memory_swappiness: "{{ item.memory_swappiness | default(None) or omit }}"
    name: "{{ item.name | default(None) or omit }}"
    network_mode: "{{ item.network_mode | default(None) or omit }}"
    networks: "{{ item.networks | default(None) or omit }}"
    oom_killer: "{{ item.oom_killer | default(None) or omit }}"
    oom_score_adj: "{{ item.oom_score_adj | default(None) or omit }}"
    paused: "{{ item.paused | default(None) or omit }}"
    pid_mode: "{{ item.pid_mode | default(None) or omit }}"
    privileged: "{{ item.privileged | default(None) or omit }}"
    published_ports: "{{ item.published_ports | default(None) or omit }}"
    pull: "{{ item.pull | default(None) or omit }}"
    purge_networks: "{{ item.purge_networks | default(None) or omit }}"
    read_only: "{{ item.read_only | default(None) or omit }}"
    recreate: "{{ item.recreate | default(None) or omit }}"
    restart: "{{ item.restart | default(None) or omit }}"
    restart_policy: "{{ item.restart_policy | default(None) or omit }}"
    restart_retries: "{{ item.restart_retries | default(None) or omit }}"
    security_opts: "{{ item.security_opts | default(None) or omit }}"
    shm_size: "{{ item.shm_size | default(None) or omit }}"
    ssl_version: "{{ item.ssl_version | default(None) or omit }}"
    state: "{{ item.state | default(None) or omit }}"
    stop_signal: "{{ item.stop_signal | default(None) or omit }}"
    stop_timeout: "{{ item.stop_timeout | default(None) or omit }}"
    sysctls: "{{ item.sysctls | default(None) or omit }}"
    timeout: "{{ item.timeout | default(None) or omit }}"
    tls: "{{ item.tls | default(None) or omit }}"
    tls_hostname: "{{ item.tls_hostname | default(None) or omit }}"
    tls_verify: "{{ item.tls_verify | default(None) or omit }}"
    tmpfs: "{{ item.tmpfs | default(None) or omit }}"
    trust_image_content: "{{ item.trust_image_content | default(None) or omit }}"
    tty: "{{ item.tty | default(None) or omit }}"
    ulimits: "{{ item.ulimits | default(None) or omit }}"
    user: "{{ item.user | default(None) or omit }}"
    uts: "{{ item.uts | default(None) or omit }}"
    volume_driver: "{{ item.volume_driver | default(None) or omit }}"
    volumes: "{{ item.volumes | default(None) or omit }}"
    volumes_from: "{{ item.volumes_from | default(None) or omit }}"
    working_dir: "{{ item.working_dir | default(None) or omit }}"
  with_items: "{{ docker_container }}"
  tags: docker
